# Generated by Django 4.1.3 on 2022-12-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_alter_auctions_initial_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='initial_bid',
            field=models.IntegerField(default=0),
        ),
    ]
