# Generated by Django 4.1.3 on 2022-12-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctions_initial_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='bidder',
        ),
    ]
